- include: development/emacs.yml
- include: development/node.yml
- include: development/lisp.yml
- include: development/lua.yml
- include: development/haskell.yml

- hosts: all
  sudo: true
  tasks:
    - name: Ensure sqlite3 command line tool is installed
      apt: name=sqlite3 state=present
